/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

//import Forms.Modelos.*;
import ConexaoBanco.Conexao;
import ConexaoBanco.ManipuladorSQL;
import Objetos.*;
import Outros.*;
import java.awt.Component;
import java.sql.ResultSet;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Thiago
 */
public class FrmCadastroServico extends javax.swing.JFrame {
    //Classes de apoio
    Conexao connector = new Conexao();
    Utilitarios toolbox = new Utilitarios();
    ManipuladorSQL sql = new ManipuladorSQL();
    private Servico seLocal;
    
    //Apoio para a conversao de cidades
    ResultSet rsCidade;
    
    //Variáveis e enums de apoio
    private ModoOperacaoForm statusForm;
    private int idServicoAtual;
    
    //Constantes
    static String tituloForm = "Cadastro de Serviços";
    static String[] tableColumnsName = {"Id","Descrição","Valor do Serviço",
        "Permite Produção?","Valor de Custo"};
    static String queryPadrao = "SELECT ID," +
                                "DESCRICAO," +
                                "VALORSERVICO," +
                                "CASE PERMITEPROD" +
                                " WHEN true THEN 'Sim'" +
                                " WHEN false THEN 'Não'" +
                                " END PERMITEPROD," +
                                "VALORCUSTO " +
                                "FROM SERVICO;";
    /**
     * Creates new form FrmCadastro_Modelo
     */
    public FrmCadastroServico() {
        initComponents();
        try {            
            connector.Conectar();
            CarregaValoresPadrao();
            AlteraModoOperacaoForm(ModoOperacaoForm.PADRAO);
            
            //Definindo um listener para a mudança de linhas da tabela
            ListSelectionModel rowListener = tblMestre.getSelectionModel();
            rowListener.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            rowListener.addListSelectionListener(new ListSelectionListenerImpl());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Houve um erro na carga desta tela: " + e,
                    "Erro!", JOptionPane.ERROR_MESSAGE);
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popTabelaPrincipal = new javax.swing.JPopupMenu();
        lblTituloForm = new javax.swing.JLabel();
        tblPrincipal = new javax.swing.JToolBar();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAlterar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tplPrincipal = new javax.swing.JTabbedPane();
        pnlMestre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMestre = new javax.swing.JTable();
        lblRegistroAtual = new javax.swing.JLabel();
        lblDe = new javax.swing.JLabel();
        lblRegistroTotal = new javax.swing.JLabel();
        lblNoDataFound = new javax.swing.JLabel();
        pnlDetalhe = new javax.swing.JPanel();
        lblCampoFtxt1 = new javax.swing.JLabel();
        ftxtDescricao = new javax.swing.JFormattedTextField();
        lblCampoFtxt2 = new javax.swing.JLabel();
        try{
            ftxtValorServico = new javax.swing.JFormattedTextField();
            lblCampoFtxt9 = new javax.swing.JLabel();
            try{
                ftxtValorCusto = new javax.swing.JFormattedTextField();
                chkPermiteProducao = new javax.swing.JCheckBox();
                pnlDicas = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                lblUsuario = new javax.swing.JLabel();
                jSeparator3 = new javax.swing.JSeparator();
                lblAjuda = new javax.swing.JLabel();
                btnMostrarTodos = new javax.swing.JButton();

                setTitle(tituloForm);
                setLocation(new java.awt.Point(0, 55));
                setMinimumSize(new java.awt.Dimension(850, 550));

                lblTituloForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblTituloForm.setText("Meus Clientes");

                tblPrincipal.setFloatable(false);
                tblPrincipal.setRollover(true);
                tblPrincipal.setToolTipText("");

                btnPrimeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/double_left-48.png"))); // NOI18N
                btnPrimeiro.setText("Primeiro");
                btnPrimeiro.setToolTipText("<html><h3>Seleciona o primeiro registro da tabela<h3>");
                btnPrimeiro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnPrimeiro.setFocusable(false);
                btnPrimeiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnPrimeiro.setIconTextGap(0);
                btnPrimeiro.setMaximumSize(new java.awt.Dimension(75, 75));
                btnPrimeiro.setMinimumSize(new java.awt.Dimension(50, 50));
                btnPrimeiro.setPreferredSize(new java.awt.Dimension(50, 50));
                btnPrimeiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnPrimeiroActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnPrimeiro);

                btnAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/left_4-48.png"))); // NOI18N
                btnAnterior.setText("Anterior");
                btnAnterior.setToolTipText("<html><h3>Seleciona o registro anterior da tabela</h3>");
                btnAnterior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnAnterior.setFocusable(false);
                btnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnAnterior.setIconTextGap(0);
                btnAnterior.setMaximumSize(new java.awt.Dimension(75, 75));
                btnAnterior.setMinimumSize(new java.awt.Dimension(50, 50));
                btnAnterior.setPreferredSize(new java.awt.Dimension(50, 50));
                btnAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnAnterior.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnAnteriorActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnAnterior);

                btnProximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/right_4-48.png"))); // NOI18N
                btnProximo.setText("Próximo");
                btnProximo.setToolTipText("<html><h3>Seleciona o próximo registro da tabela</h3>");
                btnProximo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnProximo.setFocusable(false);
                btnProximo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnProximo.setIconTextGap(0);
                btnProximo.setMaximumSize(new java.awt.Dimension(75, 75));
                btnProximo.setMinimumSize(new java.awt.Dimension(50, 50));
                btnProximo.setPreferredSize(new java.awt.Dimension(50, 50));
                btnProximo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnProximo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnProximoActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnProximo);

                btnUltimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/double_right-48.png"))); // NOI18N
                btnUltimo.setText("Ultimo");
                btnUltimo.setToolTipText("<html><h3>Seleciona o último registro da tabela</h3>");
                btnUltimo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnUltimo.setFocusable(false);
                btnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnUltimo.setIconTextGap(0);
                btnUltimo.setMaximumSize(new java.awt.Dimension(75, 75));
                btnUltimo.setMinimumSize(new java.awt.Dimension(50, 50));
                btnUltimo.setPreferredSize(new java.awt.Dimension(50, 50));
                btnUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnUltimo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnUltimoActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnUltimo);
                tblPrincipal.add(jSeparator1);

                btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit_file-48.png"))); // NOI18N
                btnAlterar.setText("Alterar");
                btnAlterar.setToolTipText("<html><h3>Altera o registro selecionado</h3>");
                btnAlterar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnAlterar.setFocusable(false);
                btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnAlterar.setIconTextGap(0);
                btnAlterar.setMaximumSize(new java.awt.Dimension(75, 75));
                btnAlterar.setMinimumSize(new java.awt.Dimension(50, 50));
                btnAlterar.setPreferredSize(new java.awt.Dimension(50, 50));
                btnAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnAlterar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnAlterarActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnAlterar);

                btnIncluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_file-48.png"))); // NOI18N
                btnIncluir.setText("Incluir");
                btnIncluir.setToolTipText("<html><h3>Inclui um novo registro</h3>");
                btnIncluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnIncluir.setFocusable(false);
                btnIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnIncluir.setIconTextGap(0);
                btnIncluir.setMaximumSize(new java.awt.Dimension(75, 75));
                btnIncluir.setMinimumSize(new java.awt.Dimension(50, 50));
                btnIncluir.setPreferredSize(new java.awt.Dimension(50, 50));
                btnIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnIncluir.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnIncluirActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnIncluir);

                btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-48.png"))); // NOI18N
                btnPesquisar.setText("Pesquisar");
                btnPesquisar.setToolTipText("<html><h3>Ativa o modo de pesquisa</h3>");
                btnPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnPesquisar.setFocusable(false);
                btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnPesquisar.setIconTextGap(0);
                btnPesquisar.setMaximumSize(new java.awt.Dimension(75, 75));
                btnPesquisar.setMinimumSize(new java.awt.Dimension(50, 50));
                btnPesquisar.setPreferredSize(new java.awt.Dimension(50, 50));
                btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnPesquisarActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnPesquisar);

                btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete_file-48.png"))); // NOI18N
                btnExcluir.setText("Excluir");
                btnExcluir.setToolTipText("<html><h3>Apaga o registro selecionado</h3>");
                btnExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnExcluir.setFocusable(false);
                btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnExcluir.setIconTextGap(0);
                btnExcluir.setMaximumSize(new java.awt.Dimension(75, 75));
                btnExcluir.setMinimumSize(new java.awt.Dimension(50, 50));
                btnExcluir.setPreferredSize(new java.awt.Dimension(50, 50));
                btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnExcluir.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnExcluirActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnExcluir);
                tblPrincipal.add(jSeparator2);

                btnConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save-48.png"))); // NOI18N
                btnConfirmar.setText("Confirmar");
                btnConfirmar.setToolTipText("<html><h3>Confirma a gravação</h3>");
                btnConfirmar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnConfirmar.setFocusable(false);
                btnConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnConfirmar.setIconTextGap(0);
                btnConfirmar.setMaximumSize(new java.awt.Dimension(75, 75));
                btnConfirmar.setMinimumSize(new java.awt.Dimension(50, 50));
                btnConfirmar.setPreferredSize(new java.awt.Dimension(50, 50));
                btnConfirmar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnConfirmarActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnConfirmar);

                btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-48.png"))); // NOI18N
                btnCancelar.setText("Cancelar");
                btnCancelar.setToolTipText("<html><h3>Cancela a gravação</h3>");
                btnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                btnCancelar.setFocusable(false);
                btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnCancelar.setIconTextGap(0);
                btnCancelar.setMaximumSize(new java.awt.Dimension(75, 75));
                btnCancelar.setMinimumSize(new java.awt.Dimension(50, 50));
                btnCancelar.setPreferredSize(new java.awt.Dimension(50, 50));
                btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnCancelarActionPerformed(evt);
                    }
                });
                tblPrincipal.add(btnCancelar);

                tplPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                tblMestre.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {

                    }
                ));
                tblMestre.setComponentPopupMenu(popTabelaPrincipal);
                jScrollPane1.setViewportView(tblMestre);

                lblRegistroAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblRegistroAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblRegistroAtual.setText("00000");

                lblDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblDe.setText("de");

                lblRegistroTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblRegistroTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblRegistroTotal.setText("00000");

                lblNoDataFound.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblNoDataFound.setForeground(new java.awt.Color(255, 0, 0));
                lblNoDataFound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblNoDataFound.setText("Sem Registros Encontrados!");

                javax.swing.GroupLayout pnlMestreLayout = new javax.swing.GroupLayout(pnlMestre);
                pnlMestre.setLayout(pnlMestreLayout);
                pnlMestreLayout.setHorizontalGroup(
                    pnlMestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                    .addGroup(pnlMestreLayout.createSequentialGroup()
                        .addComponent(lblRegistroAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblDe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRegistroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNoDataFound, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );
                pnlMestreLayout.setVerticalGroup(
                    pnlMestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMestreLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pnlMestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegistroAtual)
                            .addComponent(lblDe)
                            .addComponent(lblRegistroTotal)
                            .addComponent(lblNoDataFound))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                );

                tplPrincipal.addTab("          Pesquisas          ", pnlMestre);

                lblCampoFtxt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblCampoFtxt1.setText("Nome:");

                ftxtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                lblCampoFtxt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblCampoFtxt2.setText("Valor do Serviço: ");

            } catch (Exception e){
            }
            ftxtValorServico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

            lblCampoFtxt9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            lblCampoFtxt9.setText("Valor de Custo:");

        } catch (Exception e){
        }
        ftxtValorCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        chkPermiteProducao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkPermiteProducao.setText("Permite produção?");

        javax.swing.GroupLayout pnlDetalheLayout = new javax.swing.GroupLayout(pnlDetalhe);
        pnlDetalhe.setLayout(pnlDetalheLayout);
        pnlDetalheLayout.setHorizontalGroup(
            pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalheLayout.createSequentialGroup()
                        .addComponent(lblCampoFtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ftxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetalheLayout.createSequentialGroup()
                        .addComponent(lblCampoFtxt2)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCampoFtxt9)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkPermiteProducao)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlDetalheLayout.setVerticalGroup(
            pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampoFtxt1)
                    .addComponent(ftxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampoFtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampoFtxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPermiteProducao))
                .addGap(0, 364, Short.MAX_VALUE))
        );

        tplPrincipal.addTab("          Detalhes          ", pnlDetalhe);

        pnlDicas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(" Usuário:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAjuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlDicasLayout = new javax.swing.GroupLayout(pnlDicas);
        pnlDicas.setLayout(pnlDicasLayout);
        pnlDicasLayout.setHorizontalGroup(
            pnlDicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDicasLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDicasLayout.setVerticalGroup(
            pnlDicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDicasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnMostrarTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.setToolTipText("<html><h3>Cancela a gravação</h3>");
        btnMostrarTodos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMostrarTodos.setBorderPainted(false);
        btnMostrarTodos.setFocusable(false);
        btnMostrarTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarTodos.setMaximumSize(new java.awt.Dimension(50, 50));
        btnMostrarTodos.setMinimumSize(new java.awt.Dimension(50, 50));
        btnMostrarTodos.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMostrarTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tplPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(153, 153, 153)
                        .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(pnlDicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tblPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloForm, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplPrincipal)
                .addGap(6, 6, 6)
                .addComponent(pnlDicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlteraModoOperacaoForm(ModoOperacaoForm.ALTERACAO);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        AlteraModoOperacaoForm(ModoOperacaoForm.INCLUSAO);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        AlteraModoOperacaoForm(ModoOperacaoForm.PESQUISA);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        AlteraModoOperacaoForm(ModoOperacaoForm.EXCLUSAO);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        AlteraModoOperacaoForm(ModoOperacaoForm.PADRAO);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (tblMestre.getSelectedRow() > 0){
            tblMestre.setRowSelectionInterval(tblMestre.getSelectedRow() - 1,
                    tblMestre.getSelectedRow() - 1);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if (tblMestre.getSelectedRow() < tblMestre.getRowCount() - 1){
            tblMestre.setRowSelectionInterval(tblMestre.getSelectedRow() + 1,
                    tblMestre.getSelectedRow() + 1);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        tblMestre.setRowSelectionInterval(tblMestre.getRowCount() - 1,
                tblMestre.getRowCount() - 1);
    }//GEN-LAST:event_btnUltimoActionPerformed
   
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            String query = "";
            String message = "";
            
            switch (statusForm) {
                /*
                    INCLUSÃO DE DADOS
                */
                case INCLUSAO:
                    ValidaCamposServico();                    
                    seLocal = new Servico(ftxtDescricao.getText(),
                            Double.valueOf(ftxtValorCusto.getText()),
                            Double.valueOf(ftxtValorServico.getText()),
                            chkPermiteProducao.isSelected());

                    seLocal.InsertServico();

                    message = "Serviço " + ftxtDescricao.getText() + " incluído com sucesso!";
                    JOptionPane.showMessageDialog(this, message, "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                    query = queryPadrao;
                    break;
                
                /*
                    PESQUISA DE DADOS
                */
                case PESQUISA:
                    if (!toolbox.ValidaTextField(ftxtDescricao, false)){
                        throw new Exception("Campo 'Nome' preenchido incorretamente!");
                    }
                    
                    query = "SELECT ID," +
                            "DESCRICAO," +
                            "VALORSERVICO," +
                            "CASE PERMITEPROD" +
                            " WHEN true THEN 'Sim'" +
                            " WHEN false THEN 'Não'" +
                            " END PERMITEPROD," +
                            "VALORCUSTO " +
                            "FROM SERVICO " +
                            "WHERE DESCRICAO LIKE '%" + 
                            ftxtDescricao.getText() + "%';";
                    
                    ftxtDescricao.setText("");
                    break;

                /*
                    PESQUISA DE DADOS
                */
                case ALTERACAO:
                    // Valida os campos
                    ValidaCamposServico();
                    message = "Tem certeza que deseja alterar o serviço " + ftxtDescricao.getText() + " ?";
                    if (JOptionPane.showConfirmDialog(this, message, "Alterar serviço",
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                        
                        seLocal = new Servico(idServicoAtual,
                                ftxtDescricao.getText(),
                                Double.valueOf(ftxtValorCusto.getText()),
                                Double.valueOf(ftxtValorServico.getText()),
                                chkPermiteProducao.isSelected());

                        seLocal.UpdateServico();
                        message = "Serviço " + ftxtDescricao.getText() + " alterado com sucesso!";
                        JOptionPane.showMessageDialog(this, message, "Alterar serviço", JOptionPane.INFORMATION_MESSAGE);
                    }
                    query = queryPadrao;
                    
                    break;
            }
            AlteraModoOperacaoForm(ModoOperacaoForm.PADRAO);
            PreencheTabelaPrincipal(query);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"Falha ao efetuar operação! Mensagem: " + e.getMessage(),
                    "Ops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        PreencheTabelaPrincipal(queryPadrao);
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        tblMestre.setRowSelectionInterval(0,0);
    }//GEN-LAST:event_btnPrimeiroActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroServico().setVisible(true);
            }
        });
    }
    
    private void AlteraModoOperacaoForm(ModoOperacaoForm estado) {
        Component[] compPnlDetalhe = pnlDetalhe.getComponents();
        switch(estado){
        case PADRAO:
            statusForm = ModoOperacaoForm.PADRAO;

            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnIncluir.setEnabled(true);
            btnPesquisar.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnConfirmar.setEnabled(false);
            btnConfirmar.setText("Confirmar");
            btnPrimeiro.setEnabled(true);
            btnAnterior.setEnabled(true);
            btnProximo.setEnabled(true);
            btnUltimo.setEnabled(true);
            btnMostrarTodos.setEnabled(true);

            for (Component comp1 : compPnlDetalhe) {
                comp1.setEnabled(false);
            }

            tplPrincipal.setSelectedIndex(0);
            break;

        case PESQUISA:
            statusForm = ModoOperacaoForm.PESQUISA;

            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnIncluir.setEnabled(false);
            btnPesquisar.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnConfirmar.setText("Pesquisar");
            btnConfirmar.setEnabled(true);
            btnPrimeiro.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnProximo.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnMostrarTodos.setEnabled(false);

            for (Component comp1 : compPnlDetalhe) {
                comp1.setEnabled(false);
            }

            toolbox.ResetPanelComponents(pnlDetalhe);
            ftxtDescricao.setEnabled(true);

            tplPrincipal.setSelectedIndex(1);
            ftxtDescricao.requestFocus();
            break;

        case INCLUSAO:
            statusForm = ModoOperacaoForm.INCLUSAO;

            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnIncluir.setEnabled(false);
            btnPesquisar.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnConfirmar.setEnabled(true);
            btnConfirmar.setText("Confirmar");
            btnPrimeiro.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnProximo.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnMostrarTodos.setEnabled(false);

            for (Component comp1 : compPnlDetalhe) {
                comp1.setEnabled(true);
            }
            toolbox.ResetPanelComponents(pnlDetalhe);

            tplPrincipal.setSelectedIndex(1);
            ftxtDescricao.requestFocus();
            break;

        case EXCLUSAO:
            try {
                String aviso;
                if (tblMestre.getSelectedRow() != -1){
                    aviso = "Tem certeza que deseja excluir o serviço " + ftxtDescricao.getText() + " ?";
                    if (JOptionPane.showConfirmDialog(this, aviso, "Excluir serviço",
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        seLocal = new Servico(idServicoAtual);
                        seLocal.DeleteServico();
                        aviso = "Serviço excluído com sucesso!";
                        JOptionPane.showMessageDialog(this, aviso, "Excluir serviço", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else {
                    aviso = "Nenhum serviço selecionado!\n\nClique em um dos serviços, para poder efetuar a exclusão!";
                    JOptionPane.showMessageDialog(this, aviso, "OPS!", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,"Falha SQL! Código: " + e.getErrorCode() + 
                        ". Mensagem: " + e.getMessage(), "Ops!", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Falha genérica! Mensagem: " + e.getMessage(),
                        "Ops!", JOptionPane.ERROR_MESSAGE);
            } finally {
                PreencheTabelaPrincipal(queryPadrao);
                AlteraModoOperacaoForm(ModoOperacaoForm.PADRAO);    
            }
            break;
            
        case ALTERACAO:
            statusForm = ModoOperacaoForm.ALTERACAO;

            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnIncluir.setEnabled(false);
            btnPesquisar.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnConfirmar.setEnabled(true);
            btnConfirmar.setText("Confirmar");
            btnPrimeiro.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnProximo.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnMostrarTodos.setEnabled(false);

            for (Component comp1 : compPnlDetalhe) {
                comp1.setEnabled(true);
            }
            
            seLocal = new Servico(idServicoAtual);
            
            tplPrincipal.setSelectedIndex(1);
            ftxtDescricao.requestFocus();
            
            break;
        }  
    }

    // Funções para validação de Dados
    private void ValidaCamposServico() throws Exception{
        if (!toolbox.ValidaFTextField(ftxtDescricao, false)){
            throw new Exception("Campo 'Nome' preenchido incorretamente!");
        }
        if (!toolbox.ValidaFTextField(ftxtValorCusto, false)){
            throw new Exception("Campo 'Valor de Custo' preenchido incorretamente!");
        }
        if (!toolbox.ValidaFTextField(ftxtValorServico, false)){
            throw new Exception("Campo 'Valor do Serviço' preenchido incorretamente!");
        }
    }
    
    private void PreencheTabelaPrincipal(String query){
        try {
            toolbox.LimparTabela(tblMestre);            
            DefaultTableModel tblMestreModel = sql.GetTableData(tableColumnsName,query,tblMestre);
            if (tblMestreModel.getRowCount() == 0) {
                lblNoDataFound.setVisible(true);
            } 
            else {
                lblRegistroTotal.setText(String.valueOf(tblMestreModel.getRowCount()));
                lblRegistroAtual.setText(String.valueOf(tblMestre.getSelectedRow() + 1));
                lblNoDataFound.setVisible(false);
            } 
            tblMestre.setModel(tblMestreModel);                       
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Falha SQL! Código: " + e.getErrorCode() + 
                    ". Mensagem: " + e.getMessage(), "Ops!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Falha genérica! Mensagem: " + e.getMessage(),
                    "Ops!", JOptionPane.ERROR_MESSAGE);
        }   
    }

    private void CarregaValoresPadrao() {
        try {
            PreencheTabelaPrincipal(queryPadrao);           
            lblUsuario.setText(GerenciadorViveiros.usuarioAtual.getCodigo());
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,"Falha! Mensagem: " + e.getMessage(),
                    "Ops!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void AtualizaCampos() {
        try {
                lblRegistroAtual.setText(String.valueOf(tblMestre.getSelectedRow() + 1));
                idServicoAtual = (int) tblMestre.getValueAt(tblMestre.getSelectedRow(), 0);
                
                ftxtDescricao.setText(String.valueOf(tblMestre.getValueAt(tblMestre.getSelectedRow(), 1)));
                ftxtValorServico.setText(String.valueOf(tblMestre.getValueAt(tblMestre.getSelectedRow(), 2)));
                if (String.valueOf(tblMestre.getValueAt(tblMestre.getSelectedRow(), 3)).equals(String.valueOf("Sim"))) {
                    chkPermiteProducao.setSelected(true);
                } else {
                    chkPermiteProducao.setSelected(false);
                }
                ftxtValorCusto.setText(String.valueOf(tblMestre.getValueAt(tblMestre.getSelectedRow(), 4)));
            } catch (Exception ex) {
                lblRegistroAtual.setText("0");
            }
    }
    
    //Declaração de Listeners
    private class ListSelectionListenerImpl implements ListSelectionListener {

        public ListSelectionListenerImpl() {
        }

        @Override
        public void valueChanged(ListSelectionEvent e) {
            AtualizaCampos();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JCheckBox chkPermiteProducao;
    private javax.swing.JFormattedTextField ftxtDescricao;
    private javax.swing.JFormattedTextField ftxtValorCusto;
    private javax.swing.JFormattedTextField ftxtValorServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAjuda;
    private javax.swing.JLabel lblCampoFtxt1;
    private javax.swing.JLabel lblCampoFtxt2;
    private javax.swing.JLabel lblCampoFtxt9;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblNoDataFound;
    private javax.swing.JLabel lblRegistroAtual;
    private javax.swing.JLabel lblRegistroTotal;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlDetalhe;
    private javax.swing.JPanel pnlDicas;
    private javax.swing.JPanel pnlMestre;
    private javax.swing.JPopupMenu popTabelaPrincipal;
    private javax.swing.JTable tblMestre;
    private javax.swing.JToolBar tblPrincipal;
    private javax.swing.JTabbedPane tplPrincipal;
    // End of variables declaration//GEN-END:variables
}
